const SIZE = 21;
const FINDER = 7;

/** Top-left origins of the three QR finder squares. */
const FINDER_ORIGINS: Array<[number, number]> = [[0, 0], [0, SIZE - FINDER], [SIZE - FINDER, 0]];

function finderCell(row: number, col: number): boolean | null {
  for (const [originRow, originCol] of FINDER_ORIGINS) {
    const r = row - originRow;
    const c = col - originCol;
    if (r >= -1 && r <= FINDER && c >= -1 && c <= FINDER) {
      if (r < 0 || c < 0 || r === FINDER || c === FINDER) return false;
      return Math.min(r, c, FINDER - 1 - r, FINDER - 1 - c) !== 1;
    }
  }
  return null;
}

/**
 * Visual placeholder only: a deterministic QR-like grid derived from the code.
 * The real QR will be generated by the backend with a verifiable, non-sensitive payload.
 */
export function buildQrPattern(code: string): boolean[][] {
  let seed = [...code].reduce((acc, char) => (acc * 31 + char.charCodeAt(0)) >>> 0, 7);
  const nextBit = () => {
    seed = (seed * 1103515245 + 12345) >>> 0;
    return (seed >>> 16) % 100 < 45;
  };
  return Array.from({ length: SIZE }, (_, row) =>
    Array.from({ length: SIZE }, (_, col) => finderCell(row, col) ?? nextBit()),
  );
}
